= When To Refactor Into Generators And How
:author:    Jan-Hein Bührman
:email:     <jan-hein.buhrman@ordina.nl>
// :backend:   slidy
//:backend: revealjs
//:stem:
:max-width: 80em
:twitter-tag: @jbuhrman
:conference-tag: @FIXME
:data-uri:
:icons: font
:sourcedir: .
// beige, black, league, night, serif, simple, sky, solarized, white
:revealjs_theme: beige
// "moon" is an alternative if you don't get the syntax highlighting
// in a light theme
// 25 mins
:revealjs_totalTime: 1500
:revealjs_controlsTutorial: false
:revealjs_hash: true
:source-highlighter: highlight.js
:highlightjs-languages: gherkin
//:source-highlighter: pygments
//:highlight-style: github
//:pygments-linenums-mode: inline

include::rjs_settings.adoc[]



== Goals

After this presentation, you will ...

// [role="incremental"]

* be able to _recognize_ certain loop constructs as candidate for
  refactoring,
* know _how_ to convert these constructs into more maintainable
  _Pythonic_ code,
+
by refactoring them into an elegant pipeline of generators.
* be more acquainted with the standard library `itertools` module and
  the `more-itertools` package

// FIXME: shorter sentences on slide - put full text in notes
// FIXME: perhaps add something about TDD/Gherkin


== Topics

// [role="incremental"]

* Loops with similar code but with different start/stop/selection
  criteria
* What is refactoring
* Short intro on a Generator function
* How to recognize some "patterns" of loop constructs as refactoring
  candidates
* FIXME: what else? Add later


== Variations on Fibonacci Number Selections

.**(a fictional story)**

// [role="incremental"]

* Suppose your Product Owner requires a function that returns a list of
  all Fibonacci number less than _n_
* Who knows what a Fibonacci number is? ✋

== Fibonacci Number (definition)

[quote, Wikipedia, "Fibonacci number"]
--
In mathematics, the **Fibonacci numbers** [...] form a sequence, the
**Fibonacci sequence**, in which each number is the sum of the two
preceding ones. The sequence commonly starts from 0 and 1, [...]

Starting from 0 and 1, the next few values in the sequence are:

{empty}:: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, ...
--


== First N Fibonacci Numbers in Gherkin

[source,gherkin]
----
include::{sourcedir}/tests/features/fib_list_to.feature[lines="2.."]
----

// FIXME FIXME: perhaps the persona should be "Fibonaccista" ?

// FIXME - add a new slide here? (prevent information overflow?)
//   If yes, just repeat the GIVEN - WHEN - THEN clauses of the previous

//[role="incremental"]
//* There are many people advocating to put in-line parameters (like
//  `"10"`) between double quotes. That doesn't mean that it should be
//  seen a string of some sort, but rather as a clear indication that it
//  is a parameter.

// FIXME: also mention that Gherkin is mostly used for "business"
//   functionality (check this out on Automation Panda), but I think
//   it can be helpful for "lower level" functions as well, making it a
//   clear specification.


//[role="incremental"]
//[horizontal]
//**Given**:: Describes a stable, intial state of the system _before_ the relevant action is taken
//**When**:: Describes the _action_ that is relevant for this specific scenario
//**Then**:: Describes the _outcome_ of the action

//[role="incremental"]
//* Credits:
//  https://automationpanda.com/2017/01/26/bdd-101-the-gherkin-language
// (credits & more info: https://automationpanda.com/2017/01/26/bdd-101-the-gherkin-language/[Automation Panda])

// FIXME: Mention Pandy Knight, the owner of the Automation Panda site,
//   who has given various presentations about Python and testing


//== Implementation
// // Highlight doesn't work (yet); perhaps CSS required?? [source,python,highlight=2..5]
//[role="incremental"]
//[source,python,highlight="4,7"]
//----
//include::{sourcedir}/src/fibonacci/typeless.py[]
//----
//
//[role="incremental"]
//* Source: https://docs.python.org/3/tutorial/modules.html
//* ❓ Shall we add type annotations ❓


== Implementation

[source,python]
----
include::{sourcedir}/src/fibonacci/before.py[lines="1..8"]
----
* Source: https://docs.python.org/3/tutorial/modules.html

== Product Owner is happy and wants more

* Happy with the delivered result, the Product Owner asks for more
  functionality:

// FIXME: perhaps change the word "excited" to something else?
// [role="incremental"]
--
[quote, Happy Product Owner, More Features]
____________________________________________________________________
Can you also make a function that returns the _n_'th Fibonacci number
(counting from zero)?
____________________________________________________________________
--


=== Add Gherkin for the N'th Fibonacci number

[source,gherkin]
----
include::{sourcedir}/tests/features/fib_ordinal.feature[lines="2.."]
----
//
//[role="incremental"]
//--
//[quote, Wikipedia, Fibonacci Number]
//____________________________________________________________________
//
//[...] the next few values in the sequence are:
//
//{empty}:: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, ...
// // index::   0, 1, 2, 3, 4, 5, 6, {nbsp}7, {nbsp}8, {nbsp}9, 10, 11, {nbsp}12
//____________________________________________________________________
//--


// == Parametrized testcases (_Scenario Outlines_)
//[source,gherkin]
//----
//include::{sourcedir}/tests/features/fib_ordinal.feature[]
//----
//* Source: https://r-knott.surrey.ac.uk/Fibonacci/fibtable.html#100


== Python source for the N'th Fibonacci number

[source,python]
----
include::{sourcedir}/src/fibonacci/before.py[lines="11..18"]
----


== Now the Product Owner really gets enthusiastic!

[quote, Very Enthusiastic Product Owner, Even More features]
--
Now that we've got functions for ...

* Fibonacci numbers up to N,
* the N'th Fibonacci number,
+
..., can you also make functions that return ...
+
* the first N Fibonacci numbers,
* the largest Fibonacci number less than N, and
* the smallest Fibonacci number greater than or equal to N?
--


=== The First N Fibs (Gherkin)

[soure,gherkin]
----
include::{sourcedir}/tests/features/first_n_fibs.feature[]
----


== The First N Fibs (Python)

[source,python]
----
include::{sourcedir}/src/fibonacci/before.py[lines="21..30"]
----


=== Largest Fib Less Than N (Gherkin)

[soure,gherkin]
----
include::{sourcedir}/tests/features/largest_fib_less_than.feature[]
----


== The Largest Fib Less Than N (Python)

[source,python]
----
include::{sourcedir}/src/fibonacci/before.py[lines="33..40"]
----


=== Smallest Fib Greater/Equal N (Gherkin)

[soure,gherkin]
----
include::{sourcedir}/tests/features/smallest_fib_greater_equal.feature[]
----


== Smallest Fib Greater/Equal N (Python)

[source,python]
----
include::{sourcedir}/src/fibonacci/before.py[lines="43..48"]
----


// FIXME: THIS IN ALTERNATIVE WAY OF PRESENTING LAST 3 FIBS
//== As requested, implemented (condensed)
//[source,python]
//----
//include::{sourcedir}/src/fibonacci/before_compressed.py[lines="42..49"]
//include::{sourcedir}/src/fibonacci/before_compressed.py[lines="52..57"]
//include::{sourcedir}/src/fibonacci/before_compressed.py[lines="59..64"]
//----


== All (shortened) function bodies on one single page

[cols=2*]
|===
a|[source,python]
include::{sourcedir}/src/fibonacci/before_compressed.py[lines="25..30"]
a|[source,python]
include::{sourcedir}/src/fibonacci/before_compressed.py[lines="43..48"]

a|[source,python]
include::{sourcedir}/src/fibonacci/before_compressed.py[lines="35..38"]
a|[source,python]
include::{sourcedir}/src/fibonacci/before_compressed.py[lines="53..56"]

|Do you see a pattern? ✋
a|[source,python]
include::{sourcedir}/src/fibonacci/before_compressed.py[lines="60..63"]
|===

//[.notes]
//[cols=2*]
//|===
//|`fib_list_to`
//|`first_n_fibs`
//
//|`fib_ordinal`
//|`largest_fib_less_than`
//
//|{empty}
//|`smallest_fib_greater_equal`
//
//|===


== The pattern

[source,python]
----
def some_fib_related_func(some_parameter):
    # (SOMETIMES: INITIALIZE THE LIST)
    a, b = 0, 1  # <1>
    while "some condition or otherwise a for-loop":  # <2>
        # (SOMETIMES: APPEND SOMETHING TO THE LIST)
        a, b = b, a + b  # <3>
    return a  # OR SOMETIMES: RETURN THE LIST <4>
----
<1> The variables `a` and `b` are initialized to their initial values
<2> Some `while` or `for` loop is set up
<3> The variables `a` and `b` are assigned their new respective values
<4> The desired calculated value, or a list of these values, is returned

// FIXME: move this terminology to the beginning, where I explain the first fib func
//<1> The two Fibonacci "accumulators" are initialized
//<2> Some loop with some condition is set up
//<3> The two Fibonacci "accumulators" get their respective new values


[.notes]
--
* Now that you've seen this pattern, you start looking for ways to het rid of the apparent _redundancy_ of code.
--



== Time to Start Refactoring Your Code

**(because you don't like redundant code)**

❓ Refactoring ✋


== Refactoring

[quote, Wikipedia, "Code refactoring"]
--
In computer programming and software design, **code refactoring** is the
process of restructuring existing computer code [...] without changing
its external behavior.

Refactoring is intended to improve the design, structure, and/or
implementation of the software (its non-functional attributes), while
preserving its functionality.

Potential advantages of refactoring may include improved code
readability and reduced complexity; these can improve the source code's
maintainability and create a simpler, cleaner, or more expressive
internal architecture or object model to improve extensibility. [...]
--

== Extracting Common Parts Not Doable?

It seems impossible to extract common parts of the code into functions

It is mixed up with control flow constructs -- `while` or `for` loops

Perhaps combine the requested functions ("mode flags") ❓


== Experiment: Combine The First Two Functions


WARNING: Put on your Peril Sensitive Sunglasses{empty}footnote:[https://hitchhikers.fandom.com/wiki/Joo_Janta_200_Super-Chromatic_Peril_Sensitive_Sunglasses]


[source,python]
--
include::{sourcedir}/src/fibonacci/first_two_combined.py[lines="5..15"]
--

[.notes]
--
* Warning: what you see here, really hurts the eye
** It starts already
* Don't take this contrived example too seriously; it just demonstrates that the resulting code isn't quite _maintable_ and this isn't the way to go
--


== Refactoring The Right Way: Single Responsibility

It's all about separation of concerns

* The _common_ parts between all functions:
** producing Fibonacci numbers
* The _differing_ parts between all functions:
** counting `for` loop or `while` loop with different end-criteria
** how to further process the generated Fibonacci numbers
* The _challenge_:
** how to separate the _common_ part from the _differing_ part(s)


== Solution: Use a Fibonacci Number _Generator_

FIXME: https://en.wikipedia.org/wiki/Generator_(computer_programming)

For the speaker notes: What you have to realize, is that there is a _data producing_ part in your code. And that's the part that you can isolate.



== FIXME CURRENT END OF PRESENTATION

//== Test
//[role="incremental"]
//[horizontal]
//CPU:: Central Processing Unit
//Hard drive:: lkjldf
//RAM:: Yep I know






Some loose ends
---------------
* `dotted.DottedDict` and `dotted.DottedList` for sparse-testing (nested) structures
* Using BDD
** For unit tests
** Using it only for slow (Selenium) UI tests
* Use 3^rd^ person in your Gherkin
* Use present tense
* _One Scenario_, _One Behaviour_
** No series of steps - checks - steps - checks
* `pytest-bdd` as an alternative




Resources and Links
-------------------

Automation Panda::
    https://automationpanda.com/bdd/
    +
    https://automationpanda.com/2017/01/26/bdd-101-the-gherkin-language/
Wikipedia::
    https://en.wikipedia.org/wiki/Behavior-driven_development
Behave docs::
    https://behave.readthedocs.io/
PyHamcrest docs::
    https://pyhamcrest.readthedocs.io/
`dotted`::
    https://pypi.org/project/dotted/
Cosmic Python::
    https://www.cosmicpython.com/


Recap
-----
You've heard about the following:
[role="incremental"]
* What is Behavior Driven Development
** How it relates to Test Driven Development
** How it relates to Domain Driven Design
* How does the Gherkin language looks like
** Including various constructs within the language
* How to use `behave` as BDD tool for Python
** How to create step definitions (making the specs executable)
** How to run it
** How to select (groups of) tests
** How to use setup- and teardown-fixtures
* How to test different interfaces of your system with the same tests (slow vs fast)
** By using the `--stage` option
* Additional packages to make validating easier
** PyHamcrest for more expressive validation and better diagnostics
** `dotted.DottedDict` and `dotted.DottedList` for complex data validation (needed? desired?)
* Some pieces of advice when specifying Gherkin
** Think twice about using BDD for unit tests
** Think twice about only using BDD for slow (Selenium-based) ui tests
** Don't use Gherkin to do complex technical system setup
** Use 3^rd^ person
** Use present tense
** _one scenario_, _one behavior_
* Alternative(s) for `behave`
* Additional resources

Thank You
---------

Jan-Hein Bührman

FIXME some twitter and email handles here, I guess, perhaps a link to the presentation (QR code?)

Slides created with AsciiDoc using the "slidy" back end (https://asciidoc-py.github.io/slidy.html)

Questions
---------
.Questions
****
❓
****
